<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVmty0f1\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVmty0f1/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerVmty0f1.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerVmty0f1\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerVmty0f1\appDevDebugProjectContainer([
    'container.build_hash' => 'Vmty0f1',
    'container.build_id' => '99d07d4b',
    'container.build_time' => 1551957810,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerVmty0f1');
